### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#113]
# Problem

One of our early customers is building a calendaring application. Views need to show a subset of the events from the client view, and because events can span days (and can change what day they are scheduled for), it's complex to arrange the client view such that the correct data can be found.

For example, imagine that a calendar view is showing a week view. We need the set of events that overlap with that week. 

Without additional features from Replicache, the best that such an application can do is:

1. Scan the entire client view every time
2. Compute an index (e.g., on start-date and end-date, or by event-by-month) and send that in the client view
3. Clever use of the client view keys
  E.g., the application could use `/<year>/<month>/<eventid>` as the keys. An event's prefix is the month that it occurs within (not starts on or ends on). When viewing a week in the UI, the application queries the relevant subspace of the client view.

Let us assume that the user wants a more responsive UI than (1) will allow and does not want to bloat the client view with (2).

(3) is difficult to implement. For the calendar use case, there are at least three additional complexities:
- Events that span months. You'd have to store those with a separate prefix, e.g., `/-/<event-id>` and consider them separately on every query.
  - Though note that you're always going to have to consider some events separately -- repeating events. You don't want to expand them in the client view so they need to be computed at query time.
- Weeks that span months. The primary view in most calendar applications is a week view. Weeks frequently span months. In order to build this view you'd actually have to query/monitor two months' worth of keys.
- The fact that events' start and end dates can change. This means that "updating" an event in the UI may actually be a remove and add, and the key corresponding to a given event ID is not stable.

What can we add to Replicache to make this kind of use case easier?

# Some ideas, from complex to less

## Idea 1: auto-maintained indexes ala IndexedDB

IndexedDB is a key/value store similar to Replicache that supports first-class indexes. See https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase#example (search for `createIndex`).

Developers could tell us the fields they want indexed and we automatically maintain indexes for them. The same basic API surface we already have (e.g., `scan()`) could be used to query these indexes. Because Replicache is built on diff and prolly tree it is easy to maintain these indexes efficiently.

Pros:
* Correct. Replicache can guarantee these indexes are kept up to date properly.
* Fast. All the code can be internal to Rust.
* Could theoretically be used in the future as a primitive for some kind of query language.

Cons:
* Developers can't always get the best index for their case - you can only compute indexes using primitives we provide. In order to solve the calendar use case we started with you'd need two indexes (one for start-date and one for end-date) and you'd have to do the intersection manually in user space.
* Most work on Replicache side

## Idea 2: Couchbase-style views

Couchbase has a cool feature where you basically provide a javascript function and it calls it when rows are added/edited/removed. The output of the function yields information that couchbase uses to maintain a view. In this case, the user could supply a function that maps an event to the week it appears in. The index would thus be event-by-week, which is exactly the data the UI needs.

Pros:
* You can build the exact index you want

Cons:
* Replicache has to call out to user code during index maintenance
* If user function is not written correctly, index can be wrong --> Function must be pure. If definition of function changes, application must remember to drop and re-add index.

## Idea 3: Give developers their own local storage and let them do whatever they want

Replicache doesn't currently provide developers any local/non-synchronized state, but we easily could. If we did this, and also gave developers access to the changes in the DB right before each commit, they could maintain their own indexes.

Pros:
* Maximum control for developers
* Minimum work for replicache
* Local-only storage also seems useful for some other feature request e.g., https://github.com/rocicorp/replicache/issues/74

Cons:
* Need to carefully design onChange API so that developers don't easily create infinite loops
* Index maintenance more likely to be a performance problem

# Discarded Ideas

## Discarded Idea 1: Don't do anything in Replicache, have the client view bucket events by the containing *day*.

Instead of assigning a prefix like `/<year>/<month>/:eventid`, where the prefix is the enclosing month, why not go farther and do `/<year>/<month>/<day>/:eventid`? Then the index will be almost perfect - hardly any events span days - and there's no need to do anything special in Replicache.

This doesn't work because the calendar needs to support changing time zones smoothly (without resync). Thus is will transmit client view data in UTC. Therefore if we setup the client view with a prefix granularity of day, for users in e.g., California, it will be extremely common for events to span days and the client view will not work well as an index.

You could pick some other granularity between month and day -- e.g., 48 hours. But then the complexity gets high enough that it seems like a better tradeoff to just use months.

**Comment by whiten** [comment]
I think this bug is confounding two problems that I see as separate. The first is the question of indexes for range keys, as with calendar events, which is tricky, but I think solvable. The second is whether Replicache should offer more functionality for maintaining indexes of any kind; I see some value in this over time, but I see it as independent, not necessary at this time, and not impactful for solving the question of indexes over range keys.

To tackle the problem of indexes for range keys, I think a key observation is that what makes the problem hard are multi-day events whose timespan may be arbitrarily large. I would solve this by imposing a limit on the time span of event range keys, and simply breaking "wider" keys than this into smaller ones, say one week in duration. I'd then have 3 namespaces within the repc key range:
* The full representation of an event under a random key of say 10 base-62 characters (~60 bits of entopy) in a namespace like "events/", e.g., "events/Ab0DZ17yM37".
* The time index in a namespace like "index/", followed by, say, a base-10 encoded Unix timestamp of the start of the time range, another slash, the duration in seconds encoded in base-10, another slash, and then the event id. E.g., "index/1598392194/3600/Ab0DZ17yM37". Each key is about 33 bytes, and there'd be one for each time slot where an event occurs, or more than one for events whose duration is longer than 7 days. By storing the event id as part of the key we avoid collisions for perfectly overlapping events.
* A reverse index to find all index entries for a timestamp at "reverse/", where the event id appears first, e.g. "reverse/Ab0DZ17yM37/1598392194", to allow removing old index entries when an event is modified client-side.

Now, the benefit of capping range key "widths" is that to find all events for a time period, you'd search in "index/" for entries spanning from the start time *minus* the max width up to the end time. Because index keys are only ~33 bytes and we can trivially discard events whose end is before the start of our search, this scan is very fast, and we've capped how much of the index we need to scan. With a max width of 7 days, a day view requires scanning 8 days worth of keys, while a month view requires scanning ~38 days worth, after which the set of all event ids has been extracted and can be read in another pass.

Going back to my first paragraph, while there's certainly some benefit to having Replicache be able to maintain such indexes inherently, it seems utterly tractable to me for both the data layer and client to do so as they perform modifications. Even with delta updates supported on the data layer in the future, as long as the data layer either stores or can materialize an accurate pre-change reverse index for the client, it can send the appropriate index updates and new reverse index to the client fairly easily. If that seems annoying, another option is to also tag index entries with an event version number, such that entries that don't match this version are ignored on read, and delta updates can just always write new indexes, and only periodically do a non-delta sync to clear out stale entries.

Again, all of this to me suggests that this problem is solvable at the application level, and no indexing features are strictly required of Replicache to support this use case in v1.

**Comment by aboodman** [comment]
I agree, but I there is one key thing that you're skipping over which is the design to avoid shipping the index with the client view.

Are you saying that you don't think it matters to ship it? Or are you implying some way to create the index on the client side?

I do not believe that it is practical given the current APIs in replicache to maintain an index in the application layer purely on the client side. But it wouldn't take many additional tools to do that.

**Comment by aboodman** [comment]
PS I like this index design, regardless of how it is maintained. I don't think the "reverse index" is necessary if the primary data contains the time span (which it would).

**Comment by whiten** [comment]
I should have been more explicit, but yes, I'm suggesting that the data layer ship the index with the client view. Per the examples above, I believe this is about ~33 bytes per index entry for the forward entry, and ~30 for the reverse entry, if needed.

Can you explain the bloat concern more about sending this as an extra ~63 bytes of index per entry? I see a bloat problem if the actual calendar entry were duplicated, but I think indirecting through an event id removes this concern. My starting assumption is that between subjects, dates, URLs, attendee names and addresses, etc., most calendar entries would be closer to 500-1000 bytes, ignoring indexes.

**Comment by aboodman** [comment]
Interesting yeah I hadn't considered this. Pretty good argument. I still don't think you need the reverse entry, can you explain that more?

**Comment by whiten** [comment]
First, I think there are two places you might need a reverse index: 1) in the client-side view, and 2) in the data layer.

For the client-side view, you're right that for an event, if you can read the pre-change version of it, you can construct the index keys it would have appeared at, and construct modifications to those without a stored reverse index. I'm paranoid so I might be worried about some logic error here, but that makes the reverse index a belt-and-suspenders solution, not a need, you're right.

For the data layer, if it wants to communicate a changed entry to the client via a delta update, then it would also want to communicate any new or deleted index entries. I was going to say that a data-layer side stored reverse index was helpful here as it avoided the need to be able to read the content of an entry at the time the client currently has, but that problem would extend to the reverse index as well. With or without it, we'd need some time-aware storage to send correct deletions to a client over a delta update.

But! Using your idea of treating a calendar entry as the canonical data source, and always computing the time ranges it should appear at suggests another solution. If we lower the correctness requirements of the index from "we'll display calendar entries where they appear in the index" to "we need the index to identify all calendar entries that *may* appear over a given time range", then index deletions are no longer necessary, and/or no longer need to be timely. As long as we have some way to not have "stale" index entries cause the client to have to read an unreasonable number of calendar entries for a given time range search, we can just maintain the index sloppily, treat all calendar entries as holding their canonical times, and then either periodically or as-needed request a full (rather than delta) sync from the data layer. The need for 100% accurate index removals then disappears--and 100% accurate index *adds* are much easier to maintain over changes, and have no need for a reverse index.

How does that sound?

**Comment by aboodman** [comment]
I realized another problem with baking the "index" into the client view. The client side code will have to replicate the logic to maintain it.

While this is technically possible to do, and I guess could fit in a very strict view of a v0, I wonder if we can do something smaller that makes this task significantly easier.

For example, with just a few API changes I feel like it would be possible for applications to maintain derived data entirely on the client relatively efficiently.

**Comment by aboodman** [comment]
There's a natural question of how delta sync could play into this.

Nate outlines a few ideas above:
1. data layer could maintain a cache of index versions somewhere
2. index could include a version number
  - lazy way is to version the entire index (and return entire index in every delta sync)
  - less-lazy way is to version index entries and have client ignore all but latest version for each index entry
  - both of these require periodic full syncs to clear out old index entries

Another idea is if you had https://github.com/rocicorp/replicache/issues/74 (something like this needed for delta sync anyway) then you could have diff-server send snapshot of index to data layer as a parameter to client view request.

(1) seems like the most straightforward since data layer is already keeping per-pull state in storage anyway. 

However it is a significant increase in complexity for data layer.
