### ISSUE TITLE
let's simplify db::Write::new_snapshot

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#115]
As I'm wiring pull into the db I'm finding that i think db::Write::new_snapshot should work differently. Here's how it works now:

https://github.com/rocicorp/repc/blob/master/src/db/write.rs#L84

The primary specific issues is that new_snapshot assumes that i want the current commit at the given named head to be the basis for my new snapshot. but I don't: I want to set the named head to a new commit which has a basis somewhere near the head of the main named chain (the base snapshot).

A second thing is that it reads the entire map of the basis into memory. this looks like a carryover from the new_local implementation, where it makes sense. for sync i'm not sure it does. if the way we patch the base map from a pullresponse is that we call new_snapshot to get a db::Write and then patch the Write's map then we are holding a write lock all the while we do the patching. Maybe this isn't the end of the world but it's a little awkward. I think what i want to do is read the map of the base snapshot, apply the patch we just pulled, call something that looks more like Commit::new_snapshot https://github.com/rocicorp/repc/blob/d41e3392b6a619ad40b5221860e752a917152400/src/db/commit.rs#L45 to get a commit, and then acquire a write lock, write it, and then tell it to commit.

(Note if for symmetry's sake you want new_snapshot to work like new_local, where we call new_snapshot to get a Write which we use to patch the map and then call commit --that's fine by me. i can just fix the basis assumption.)

@aboodman i think you might be fiddling with these interfaces so putting this in an issue if you have a thought. i'm inclined to just address the basis assumption as part of my pr and then if we want to do something more later we can.

**Comment by aboodman** [comment]
On Sun, Aug 23, 2020 at 7:28 PM Phritz <notifications@github.com> wrote:

> As I'm wiring pull into the db I'm finding that i think
> db::Write::new_snapshot should work differently. Here's how it works now:
>
> https://github.com/rocicorp/repc/blob/master/src/db/write.rs#L84
>
> The primary specific issues is that new_snapshot assumes that i want the
> current commit at the given named head to be the basis for my new snapshot.
> but I don't: I want to set the named head to a new commit which has a basis
> somewhere near the head of the main named chain (the base snapshot).
>
I might be misunderstanding but I believe the API supports what you want
as-is. You can say Commit::new_snapshot(Whence::Hash(base_snapshot)...) to
create a new snapshot commit with a basis of whatever hash you want. Isn't
that what you need? Later you can commit to whatever head you want by
passing the a head name to the commit() method.

> A second thing is that it reads the entire map of the basis into memory.
> this looks like a carryover from the new_local implementation, where it
> makes sense. for sync i'm not sure it does.
>
The reason the entire map for basis is read into memory is because we don't
have real prolly trees yet, just a fake implementation. Later it won't do
that. We don't want it for new_local either, really.

> if the way we patch the map from a pulled server state is that we call
> new_snapshot to get a db::Write then patch that the Write's map then we are
> holding a write lock all the while we do the patching.
>
Maybe this isn't the end of the world but it's a little awkward. I think
> what i want to do is read the map of the base snapshot, apply the patch we
> just pulled
>
This seems like a separate issue from the above two to me. I do not think
that it is possible to apply a patch at all with the current high-level
design without holding a write lock. Prolly tree mutations require some
place to queue mutations which get flushed atomically as part of commit. It
makes a lot of sense to reuse the write transaction for this.

Also I do not think it is a big problem to hold the write lock for the
duration of applying the patch, as long as the fetch isn't part of that.

> @aboodman <https://github.com/aboodman> i think you might be fiddling
> with these interfaces so putting this in an issue if you have a thought. if
> you are not currently fiddling then i'm happy for either of us to make a
> change.
>
Not currently fiddling. This sort of thing is why I was kind of worried
about a different person doing the low level pieces than the high level
pieces. Easy to not match up. But I *think* in this case we have what you
need?

**Comment by phritz** [comment]
indeed. see slack comment about brain not working.

**Comment by aboodman** [comment]
all good dude.
