### ISSUE TITLE
Ensure that overlapping syncs don't emit a loud/scary warning

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#147]
This is expected in the case of multiple tabs.

**Comment by phritz** [comment]
sorry this is a long addendum to what seemed like a simple thing but i want to be sure we are doing the right thing here. 

the general thinking is that if there are two concurrent syncs the one that started last should effectively cancel the first to avoid deadlocking the sync protocol. specific behavior is as follows:
- beginsync rpc:
   - beginsync returns BeginSyncError::OverlappingSyncs when it detects that another sync has *completed* between the time that beginsync started and when it is about to return, having pulled new state. 
   - beginsync does not detect that another sync is in progress when it starts or completes because of the general thinking above. if there are concurrent beginsync calls the one completing last "wins": the loser will error out in maybeendsync (see below). if there is sync that is already in progress its beginsync call having returned and beginsync is called again this new sync also wins: the sync that was in progress will error out in maybeendsync (or sooner if we have gc or a new check in opentransaction, see below).
- maybeendsync rpc:
   - maybeendsync will return MaybeEndSyncError::WrongSyncHead if it detects that another sync has *started* (that a new beginsync call has returned). 
   - maybeendsync will return MaybeEndSyncError::OverlappingSyncs if it detects that another sync has *completed* since it started. 
- opentransaction
   - if another sync completes its beginsync call while txs are being replayed by a first sync then 
      - (eventually when we have garbage collection) the next time the first calls opentransaction with a replay it will fail with a db error because its sync chain will have been gc'd, likely returning OpenTransactionError::DBWriteError https://github.com/rocicorp/repc/blob/20cdf52968a0dc06f5791948bf3fccb3b7c5881f/src/embed/connection.rs#L222 
      - (now given that we do not have gc) the opentransaction call will succeed even though it is building on a chain that has no hope of being used. there is a [prescient TODO](https://github.com/rocicorp/repc/blob/20cdf52968a0dc06f5791948bf3fccb3b7c5881f/src/embed/connection.rs#L252) musing whether we should enforce that if we are opening a replayed transaction its basis must be the current synchead. I think we should add this check so we can error out cleaning here with an overlappingsyncs error.
- committransaction
   - there is no check when committing a replay transaction to the sync chain that the new commit's basis is the current sync head. without gc and without the check mentioned above there is nothing stopping concurrently replaying syncs from clobbering each others sync heads so this is another argument to put the check in opentransaction above.

something we need to think carefully about is overlapping syncs that might be building the same sync chain. suppose (as I think is the case) that commits do not contain a unique identifier or timestamp so that two snapshots containing the same map, last mutation id, server state id, etc will have exactly the same hash. then it is possible for two syncs to start building the same sync chain, unaware of one another. suppose they both pull the same server state. they will both set the sync head to identical commits (the second being effectively a nop) when they return from beginsync and start building on it (it is a new base snapshot). without the opentransaction check above they could keep replaying the same commits until one completes and the other gets a WrongSyncHead from maybeendsync. i can't think of anything bad happening here except doing extra useless work and seeing confusing log lines, but this is another argument for the opentransaction check.

ok whew. zooming out i think the task here is:
1. [phritz] add the check to opentransaction mentioned above that enforces that the basis of a replay transaction must be the current sync head, returning OpenTransactionError::WrongSyncHead if it is not. (i'm suggesting not returning OverlappingSync for this case because though likely it is not necessarily an overlapping sync that caused this, could be a bindings bug). 
2. [?] ensure the js sdk logs doesn't scare customers when we hit an overlapping sync. i think this means to ensure we log info instead of error (recall we prefer to not use warn) when:
   - beginsync returns BeginSyncError::OverlappingSyncs
   - opentransaction returns OpenTransactionError::WrongSyncHead (which i will add shortly)
   - maybeendsync returns MaybeEndSync::WrongSyncHead or ::OverlappingSyncs

I do not think we need to add randomness/timing to commits to make them unique for the purposes of overlapping syncs unless I'm missing something, quite possible.

Tweaks, differences of opinion?

**Comment by aboodman** [comment]
The only thing is that I think it may be fairly common to have overlapping syncs in a web browser. Multiple tabs with same app is pretty common situation, for me, and I think others.

Is it possible to detect this earlier, so we don't have multiple tabs doing useless work?

**Comment by phritz** [comment]
is there one instance of repc per tab or per browser?

**Comment by aboodman** [comment]
Per tab.

**Comment by phritz** [comment]
All that's left in order to close this is:
1. when calling dispatch from javascript if we get an error do not log it scarily if the error string contains "JSLogInfo". Just log non-scarily (eg, info) in that case. We return some JSLogInfo errors from beginsync, opentransaction, and maybeendsync if that is useful.
1. release new js with this change
1. release new repc with https://github.com/rocicorp/repc/pull/170/commits/dc29e5f8734a456fb261edaa1d59e846d3618bbd
