### ISSUE TITLE
IDBStore needs to listen to change events (from other tabs)

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#163]
The implementation of replicache-client could assume that all changes flowed through its own instance since we ensured there was only one connection to each noms db. Because of tabs we can no longer make this assumption.

**Comment by aboodman** [comment]
Related: #161

**Comment by arv** [comment]
IndexDB does not support this. There is a proposal to add IDBObserver but it is not implemented anywhere.

## Proposal:

- Use a `sessionStorage` (I think that should be enough instead of localStorage) and write the rootHash of head after each mutation.
- Listen to `window.onstorage` and compare the hashes.

TODO: Define what to do when hashes diverge. Maybe it is enough to just fire all subscriptions? sync?

**Comment by aboodman** [comment]
> IndexDB does not support this

Argh, piece of junk.

**Comment by aboodman** [comment]
> TODO: Define what to do when hashes diverge. Maybe it is enough to just fire all subscriptions? sync?

The same as what happens when we sync! It's just sync via a different channel sort of.

**Comment by aboodman** [comment]
🔥
