### ISSUE TITLE
RFC: Storage interface

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#2]
This is a proposal for how low-level storage could work in repc. It differs from Noms and the existing replicache-client. Comments and feedback are appreciated.

# History

Noms originally defined a low-level storage interface which was inspired by Camlistore (née Perkeep). In Go, it was basically:

```
type Chunk []byte

type ChunkStore interface {
  // Not defined originally, but over time we came to expect these had read-your-writes semantics.
  Put(Chunk) (Hash, error)
  Get(h Hash) (Chunk, error)
  Has(h Hash) (bool, error)
  // Note: no Del() -- GC is implied, but how to implement is complex

  // Single mutable piece of state, must support atomic compare and set.
  Root() (Hash, error)
  SetRoot(h Hash, prev Hash) (error)
}
```

Though elegant, a number of problems emerged with this design over the lifetime of the project. Some of those begat changes to the interface, others were just worked around. These are some of the problems:

* It was impractical to have the ChunkStore define the hash for a chunk because many other bits of code higher in the stack need the hash for a chunk before it is written to storage.
* It was impractical to write a Chunk through to persistent storage eagerly, which created many layers of ad-hoc caching, which worked against having a clear sense of isolation semantics
* The isolation implied by Root/SetRoot was not complete: details of one logical transaction leaked through to other transactions via `Has`
  * Eventually, a sort of pseudo-transactional system was created where Puts were queued in an instance of ChunkStore (either in memory or spilled to temporary storage), and SetRoot flushed those changes.
* Most crucially: it was never clear how exactly to implement GC. Without a clear sense of transactions, chunks written by one thread/process just kind of hung in space until committed. Should those be eligible for GC or not? For Noms it was OK to handwave this to the future, but it is critical for Replicache.

So doing this again, I'd like to think more carefully about what this low-level interface should look like. It needs to be something that fulfills the needs of Replicache. It needs to be implementable on the platforms we want to run on. It needs to be fast. It *does not* need to be minimal.

# Proposal

Rather than having the low-level storage abstraction be a content addressed store, it's just a plain key/value store. Also we require implementations of the interface to implement [Strict Serializability](https://jepsen.io/consistency/models/strict-serializable) transactions.

Sketch (again in Go, I don't have Rust under my fingers enough yet):

```
type KVStore interface {
  KVSource
  KVSink
}

type KVSource interface {
  Read() (ReadTransaction, error)
}

type KVSink interface {
  Write() (WriteTransaction, error)
}

type ReadTransaction interface {
  Has(key []byte) (bool, error)
  Get(key []byte) (bool, []byte, error)
  // Scan()? I can't think of a case where Scan() would be needed, currently.
}

type WriteTransaction interface {
  ReadTransaction

  Set(key, val []byte) error
  Del(key) error

  Abort() error
  Commit() error
}
```

On the web, this can be implemented using IndexedDB, with two caveats:

* The IndexedDB [spec](https://www.w3.org/TR/IndexedDB-2/#transaction-lifetime-concept) was not written with db terminology, so it's hard to absolutely convince myself it is guaranteed to be at least strict serializable, but I think that's true. We need to verify this.
* IndexedDB transactions are not explicitly committed -- they automatically commit after all outstanding requests return. What this means in practice is that developers cannot perform asynchronous work between `Transact()` and `Commit()`. If they do, it just means that operations against the transaction will begin failing. That seems fine (we don't really want/expect people to do this either).

On mobile/desktop, this can obviously be implemented against SQLite. I believe that it can also be implemented against something like LevelDB using a combination of [snapshots](https://github.com/google/leveldb/blob/master/doc/index.md#snapshots) and [batched writes](https://github.com/google/leveldb/blob/master/doc/index.md#atomic-updates).

# Usage Sketch

See #3

**Comment by whiten** [comment]
I like the overall shape of this, and think basing this API on a simple []byte -> []byte mapping will allow for low levels of extraneous processing on the parts of chunks that aren't being modified.
A few changes I'd suggest:

- I'd specialize Transact() for whether writes are permitted. This is baked into the IndexedDB spec where transactions are opened with a mode and only one readwrite transaction per object store (table) may be open at once. I believe this will allow for multiple reads to be performed in parallel where otherwise one read having to go to disk at the third level may block another read from even starting until that disk read is resolved.
- Expanding the above, I'd split Transaction into read and write variants to let the compiler enforce method access. WriteTransaction is then a superset of the ReadTransaction interface.
ReadTransaction should gain a Rollback/Cancel/Abort() method, to let callers explicitly indicate an end to the lifetime. For WriteTransactions, I do believe there'll be times we decide after some reads to abort, and should have a way to do this.
- I'm iffy on Del() and the GC outline presented. Is Del() supposed to indicate that a ref is being removed, or the final ref was removed? (That is, do you imagine ref counting is happening in the chunk store layer, or above it?) As a potential alternative, I can imagine an additional parameter to Put() that is the set of keys that the key being put refers to. The previous version of this set would then need to be read implicitly as part of the Put(), and then inc and decrefs flow from any keys present in one set but not the other. Del() goes away, and we'd further decref any keys previously referred to by keys whose refcounts fell to zero as part of the transaction.
- Also regarding GC, the discussion so far is about the design, but I think it's even more important to nail down the spec. I think the above proposal makes that more clear, but we should also document timing; that is, chunks may be permanently deleted as soon as a Commit() is issued on a transaction that has changed the reference count a key to zero, but these deletions are not guaranteed to be performed immediately. In the span between when a reference goes to zero and the deletes occur, Has() or Get() calls against a key will/(or not) accurately represent the final reference count of a key.
- Regarding the problem of roots, maybe keys may optionally reference themselves in their refs list? Or maybe only a special key called "head" or something can? (If any key can, it's easy to introduce leaks unless we provide more methods to enumerate keys and read the refs list for them.)
- I'd opt out of the extra bool return for Get(), but that's just a personal preference.
- In time, at least for Set(), I expect we may want variants that accept a cord-like data structure to cut down on memcpys of the unmodified sections. No semantic changes, so this choice can be made down the line.

**Comment by aboodman** [comment]
(Forwarded comments from Nate White)

> I like the overall shape of this, and think basing this API on a simple []byte -> []byte mapping will allow for low levels of extraneous processing on the parts of chunks that aren't being modified.
> A few changes I'd suggest:
> I'd specialize Transact() for whether writes are permitted. This is baked into the IndexedDB spec where transactions are opened with a mode and only one readwrite transaction per object store (table) may be open at once. I believe this will allow for multiple reads to be performed in parallel where otherwise one read having to go to disk at the third level may block another read from even starting until that disk read is resolved.

I considered this, and I guess there's really no reason *not* to do it since it allows more implementation strategies. But my idea was that at this level storage would be optimistically locked -- multiple read and write transactions can proceed in parallel with snapshot isolation, but concurrent writes will bounce on optimistic lock failure.

In practice the layer above would typically execute writes serially, though (this is how we have it setup with Noms, too).

But it seems like maybe I'm missing something important?

> Expanding the above, I'd split Transaction into read and write variants to let the compiler enforce method access. WriteTransaction is then a superset of the ReadTransaction interface.
ReadTransaction should gain a Rollback/Cancel/Abort() method, to let callers explicitly indicate an end to the lifetime. For WriteTransactions, I do believe there'll be times we decide after some reads to abort, and should have a way to do this.

If there are implementations of this that use pessimistic locking then abort makes sense, but if they all use optimistic locking then does it still? The reason I pause on having an explicit abort method is that whenever there's an abort method I always wonder what its semantics are -- am I *required* to call it? Is it a perf problem if I fail to? etc.

> I'm iffy on Del() and the GC outline presented. Is Del() supposed to indicate that a ref is being removed, or the final ref was removed? (That is, do you imagine ref counting is happening in the chunk store layer, or above it?)

I imagined ref counting happening at the layer above, but using this low level storage interface to store the counts. In other words, this is just a transactional key/value store. There's no concept of ref counting here.

> As a potential alternative, I can imagine an additional parameter to Put() that is the set of keys that the key being put refers to. The previous version of this set would then need to be read implicitly as part of the Put(), and then inc and decrefs flow from any keys present in one set but not the other. Del() goes away, and we'd further decref any keys previously referred to by keys whose refcounts fell to zero as part of the transaction.

Hm, but if we do that it pulls the implementation of GC down into this interface, which seems undesirable if we are to have multiple implementations. What are the advantages to having it here vs the layer above?

> Also regarding GC, the discussion so far is about the design, but I think it's even more important to nail down the spec. I think the above proposal makes that more clear, but we should also document timing; that is, chunks may be permanently deleted as soon as a Commit() is issued on a transaction that has changed the reference count a key to zero, but these deletions are not guaranteed to be performed immediately. In the span between when a reference goes to zero and the deletes occur, Has() or Get() calls against a key will/(or not) accurately represent the final reference count of a key.

It does seem weird to that a key may be present for some undetermined time after a transaction commits and its refcount has dropped to zero, but I also don't like the idea of committing to removing them synchronously.

I can't think of a concrete problem to this behavior, but it seems wrong. Do you have any ideas to avoid it?

> Regarding the problem of roots, maybe keys may optionally reference themselves in their refs list? Or maybe only a special key called "head" or something can? (If any key can, it's easy to introduce leaks unless we provide more methods to enumerate keys and read the refs list for them.)

You mean the problem of the sync head? I think it is fine to just change sync to require those heads to be rooted, rather than introduce something special .

> I'd opt out of the extra bool return for Get(), but that's just a personal preference.

I guess it's irrelevant because in Rust it would return `Result<Option<[u8]>>`. Or are you saying that you don't think it is worth callers being able to distinguish the db having an empty value for a key and not having a key?

> In time, at least for Set(), I expect we may want variants that accept a cord-like data structure to cut down on memcpys of the unmodified sections. No semantic changes, so this choice can be made down the line.

Makes sense, that would be exciting.

**Comment by whiten** [comment]
> > I'd specialize Transact() for whether writes are permitted. This is baked into the IndexedDB spec where transactions are opened with a mode and only one readwrite transaction per object store (table) may be open at once. I believe this will allow for multiple reads to be performed in parallel where otherwise one read having to go to disk at the third level may block another read from even starting until that disk read is resolved.
> 
> I considered this, and I guess there's really no reason _not_ to do it since it allows more implementation strategies. But my idea was that at this level storage would be optimistically locked -- multiple read and write transactions can proceed in parallel with snapshot isolation, but concurrent writes will bounce on optimistic lock failure.
> 
> In practice the layer above would typically execute writes serially, though (this is how we have it setup with Noms, too).
> 
> But it seems like maybe I'm missing something important?

From https://www.w3.org/TR/IndexedDB-2/#transaction-mode and https://w3c.github.io/IndexedDB/#transaction-scheduling, it appears that IndexedDB locks the whole object store pessimistically when a `readwrite` transaction is opened. 

> > Expanding the above, I'd split Transaction into read and write variants to let the compiler enforce method access. WriteTransaction is then a superset of the ReadTransaction interface.
> > ReadTransaction should gain a Rollback/Cancel/Abort() method, to let callers explicitly indicate an end to the lifetime. For WriteTransactions, I do believe there'll be times we decide after some reads to abort, and should have a way to do this.
> 
> If there are implementations of this that use pessimistic locking then abort makes sense, but if they all use optimistic locking then does it still? The reason I pause on having an explicit abort method is that whenever there's an abort method I always wonder what its semantics are -- am I _required_ to call it? Is it a perf problem if I fail to? etc.

Because IndexedDB imposes pessimistic transactions at the object store level, we'll want callers to indicate the end of their use of even read-only transactions as soon as they're done with them, as we can't start a `readwrite` transaction until all prior `readonly` ones are completed. And so yet, I believe these calls are required by callers, and in a timely manner no less. Does that sound right, or am _I_ missing a detail here?

> > I'm iffy on Del() and the GC outline presented. Is Del() supposed to indicate that a ref is being removed, or the final ref was removed? (That is, do you imagine ref counting is happening in the chunk store layer, or above it?)
> 
> I imagined ref counting happening at the layer above, but using this low level storage interface to store the counts. In other words, this is just a transactional key/value store. There's no concept of ref counting here.

Sure, I should have played that possibility out in my mind more. If the counting is happening above this layer and `Del()` is definitive, then this works fine. I was forgetting that we expect at least two implementations of ChunkStore vs. one for the layer above it, and given that I agree it makes sense to keep this logic above.
 
> It does seem weird to that a key may be present for some undetermined time after a transaction commits and its refcount has dropped to zero, but I also don't like the idea of committing to removing them synchronously.
> 
> I can't think of a concrete problem to this behavior, but it seems wrong. Do you have any ideas to avoid it?

Yeah, I agree this would be lame. I don't have great ideas under my proposal, but I think this problem isn't present if the refcounts are maintained one level up. I agree with your desire to make GC happen asynchronously from user-directed transactions, and think that's probably doable. I don't have a concrete design in my head yet, but I keep envisioning queues of ref-modifying operations that are cheaply appended to during transactions, and then lazily evaluated to produce concrete counts allowing for chunk removal.

> > Regarding the problem of roots, maybe keys may optionally reference themselves in their refs list? Or maybe only a special key called "head" or something can? (If any key can, it's easy to introduce leaks unless we provide more methods to enumerate keys and read the refs list for them.)
> 
> You mean the problem of the sync head? I think it is fine to just change sync to require those heads to be rooted, rather than introduce something special .

👍

> > I'd opt out of the extra bool return for Get(), but that's just a personal preference.
> 
> I guess it's irrelevant because in Rust it would return `Result<Option<[u8]>>`. Or are you saying that you don't think it is worth callers being able to distinguish the db having an empty value for a key and not having a key?

I do think it should be possible to differentiate between absence and an empty value; in neither Go nor Rust did an extra bool result seem necessary to do this.

> > In time, at least for Set(), I expect we may want variants that accept a cord-like data structure to cut down on memcpys of the unmodified sections. No semantic changes, so this choice can be made down the line.
> 
> Makes sense, that would be exciting.

**Comment by phritz** [comment]
Dictating so apologies

- is it possible that we want something stronger than snapshot isolation? In particular the two paragraphs about real-time guarantees and ordering make me wonder if replica can make the guarantees that I think we want to make when built on a chunk store that has those properties.

- I think it would be bad if chunk store or the layer above have different semantics depending on the implementation. I can easily imagine that using different databases under the hood could admit subtle behavioral differences. For this reason I think we might consider making more and more explicit statements about the expected Behavior of chunk store. That way we can carefully check how closely the implementation matches what we want and know where we have to add some Machinery at a level above the database to bring Its Behavior in line with what we expect. Questions like the real time and ordering guarantees or lack thereof and whether it is read after write seem like a good place to start. Given our use case we might want to err on the side of easy to reason about for the developer using the chunk store interface as opposed to high performance (ie we are not doing read your rights over the network).

- it might be nice to call the higher-level thing something other than "database". There is already going to be a database at the lowest layer namely sqlite or similar. We should definitely not do the noms thing where we have a thingy of the same name at different levels. 

- in the trunk store interface I might have expected multi get and multiset were you can read or write number of chunks at one time instead of the single chunk oriented interface described above. I'm saying this as someone who knows very little about how all this is going to actually work or about how Noms works. I have no idea if that would be an important aspect of making it efficient but it would be kind of natural based on how I understand the chunk store will be used.

- for garbage collection if we are going to do ref Counting is it simplest to just let deletions happen synchronously? Like everyone expects big writes take longer than little writes and so if synchronicity yields a big simplification win then why not big deletions just take longer than little deletions? I'm not sure exactly how to value asynchronous deletions versus a potentially simpler and more predictable mental model and implementation. I know you guys are leaning towards asynchronous deletion and that is appealing on many levels but I guess I'm asking at what cost -- i love it when things are super predictable and easy to reason about.

- for the hanging sink head problem it's a pretty simple rule to reason about you just say that it has to be in the graph. If something is not reachable through the graph then it gets garbage collected. Is there any kind of eager writing that would make this problematic like for example do you have to write chunks in the order in which they are found in the graph?

- to maximize our choice of implementations for chunk store it seems like we probably need to have an explicit rollback or abort or some other way to track the life cycle of a transaction. If we don't then we can't use anything under the hood that requires explicit cleanup of a transaction

- I'm a little unclear in the model described above where the concept of graph comes in. Is it something that is hidden under the hood of a map or is a map part of a type system like in Noms? Or does it come in because we are treating the value bites as Json?

Generally looks pretty good to me!

**Comment by aboodman** [comment]
> is it possible that we want something stronger than snapshot isolation? In particular, the two paragraphs about real-time guarantees and ordering make me wonder if replica can make the guarantees that I think we want to make when built on a chunk store that has those properties.

Good point, I'll think harder about this. Given @whiten's observation about the semantics of indexeddb, we might have no choice but to change this.

> I think it would be bad if chunk store or the layer above have different semantics depending on the implementation...

Agree. It's tempting to abstract, but important to re-state: we don't intend for anyone else to use this. It's an implementation detail of our code. We should just write the thing we need, directly. Will re-evaluate in that light.

> it might be nice to call the higher-level thing something other than "database". There is already going to be a database at the lowest layer namely sqlite or similar. We should definitely not do the noms thing where we have a thingy of the same name at different levels.

Will do. Maybe this thing is a chunk store, and the thing above is a map store, or versioned store, or something.

> in the chunk store interface I might have expected multi get and multiset were you can read or write number of chunks at one time instead of the single chunk oriented interface described above. I'm saying this as someone who knows very little about how all this is going to actually work or about how Noms works. I have no idea if that would be an important aspect of making it efficient but it would be kind of natural based on how I understand the chunk store will be used.

I think it's not necessary given the presence of transactions... the same performance optimizations that would be achievable with multiset/get are achievable with transactions.

> for garbage collection if we are going to do ref Counting is it simplest to just let deletions happen synchronously?

Definitely. It's just that this is always the first thing that ref-counting sytems weaken to get better performance. See, e.g., https://abramov.io/rust-dropping-things-in-another-thread. So I wanted to think ahead about whether it was *possible* to do this if/when we wanted to. I don't want to do it on day one. If there is significant additional complexity to doing it, we would likely still choose the simpler way initially and pay the cost later.

> Is there any kind of eager writing that would make this problematic like for example do you have to write chunks in the order in which they are found in the graph?

I can't think of any. I think it should be invariant in this system (as in Noms) that all chunks are complete -- there are no committed dangling references. But because of transactions we can actually write the chunks in any order so long as they are all there at commit time.

> to maximize our choice of implementations for chunk store it seems like we probably need to have an explicit rollback or abort or some other way to track the life cycle of a transaction. If we don't then we can't use anything under the hood that requires explicit cleanup of a transaction

Fair.

> I'm a little unclear in the model described above where the concept of graph comes in. Is it something that is hidden under the hood of a map or is a map part of a type system like in Noms? Or does it come in because we are treating the value bytes as Json?

The values at this layer are encoded "chunks" which each can encode references to other chunks. I hadn't thought yet about what they should be serialized as. I'm hoping that it can be a lot simpler than Noms since we don't care about types and all of that business.

**Comment by arv** [comment]
Good discussion so far...

I feel like there is a lot of implied behavior here when it comes to GC. There is no mention how you determine what a ref is? I'm assuming there is a layer on top of this that is somewhat similar to Noms that defines how a value references another key (or value) for this discussion.

**Comment by aboodman** [comment]
Yeah, sorry. I'm assuming a few layers on top of this roughly analagous (but simpler than) Noms' `Value` and `Database` layers. Those layers would implement the prolly tree, chunking, references, etc.

What this layer is trying to do is just provide sufficient functionality to actually implement reference counting correctly.

**Comment by aboodman** [comment]
> I do think it should be possible to differentiate between absence and an empty value; in neither Go nor Rust did an extra bool result seem necessary to do this.

@whiten - How do you have in mind to distinguish them in Go? It's idiomatic in Go to have these ["ok" bools](https://blog.toshima.ru/2019/07/21/go-comma-ok-idiom.html) I thought precisely because it's hard to distinguish otherwise.

**Comment by aboodman** [comment]
Thank you for all the feedback. I believe I have addressed all of it and updated the top comment.

Details below:

@whiten:
> I like the overall shape of this, and think basing this API on a simple []byte -> []byte mapping will allow for low levels of extraneous processing on the parts of chunks that aren't being modified.
> A few changes I'd suggest:
> I'd specialize Transact() for whether writes are permitted. This is baked into the IndexedDB spec where transactions are opened with a mode and only one readwrite transaction per object store (table) may be open at once. I believe this will allow for multiple reads to be performed in parallel where otherwise one read having to go to disk at the third level may block another read from even starting until that disk read is resolved.

> Expanding the above, I'd split Transaction into read and write variants to let the compiler enforce method access. WriteTransaction is then a superset of the ReadTransaction interface.
> ReadTransaction should gain a Rollback/Cancel/Abort() method, to let callers explicitly indicate an end to the lifetime. For WriteTransactions, I do believe there'll be times we decide after some reads to abort, and should have a way to do this.

@phritz:

> to maximize our choice of implementations for chunk store it seems like we probably need to have an explicit rollback or abort or some other way to track the life cycle of a transaction. If we don't then we can't use anything under the hood that requires explicit cleanup of a transaction

Good points. I've split Read/Write transactions apart and added explicit abort. I also copied this pattern to the higher layers.

@whiten:
> Also regarding GC, the discussion so far is about the design, but I think it's even more important to nail down the spec. I think the above proposal makes that more clear, but we should also document timing; that is, chunks may be permanently deleted as soon as a Commit() is issued on a transaction that has changed the reference count a key to zero, but these deletions are not guaranteed to be performed immediately. In the span between when a reference goes to zero and the deletes occur, Has() or Get() calls against a key will/(or not) accurately represent the final reference count of a key.

> Yeah, I agree this would be lame. I don't have great ideas under my proposal, but I think this problem isn't present if the refcounts are maintained one level up. I agree with your desire to make GC happen asynchronously from user-directed transactions, and think that's probably doable. I don't have a concrete design in my head yet, but I keep envisioning queues of ref-modifying operations that are cheaply appended to during transactions, and then lazily evaluated to produce concrete counts allowing for chunk removal.

@phritz:
> for garbage collection if we are going to do ref Counting is it simplest to just let deletions happen synchronously? Like everyone expects big writes take longer than little writes and so if synchronicity yields a big simplification win then why not big deletions just take longer than little deletions? I'm not sure exactly how to value asynchronous deletions versus a potentially simpler and more predictable mental model and implementation. I know you guys are leaning towards asynchronous deletion and that is appealing on many levels but I guess I'm asking at what cost -- i love it when things are super predictable and easy to reason about.

I agree with Nate's sketch for how async GC could theroetically work and with Phritz to lean toward simplicity. In #3, I committed to GC appearing to take effect synchronously. If we ever decide to implement it asynchronously, I'm confident there are ways to not break the illusion. Anyway, we can always weaken the contract if necessary -- we are the only clients of this.

@whiten:
> Because IndexedDB imposes pessimistic transactions at the object store level, we'll want callers to indicate the end of their use of even read-only transactions as soon as they're done with them, as we can't start a readwrite transaction until all prior readonly ones are completed. And so yet, I believe these calls are required by callers, and in a timely manner no less. Does that sound right, or am I missing a detail here?

@phritz:

> is it possible that we want something stronger than snapshot isolation? In particular, the two paragraphs about real-time guarantees and ordering make me wonder if replica can make the guarantees that I think we want to make when built on a chunk store that has those properties.

I changed this interface to be similarly pessimistic and also changed the documentation to commit to strictly serialized transactions, not snapshot.

Fritz is right that we don't need snapshot isolation for such a small datastore.

@whiten:

> I do think it should be possible to differentiate between absence and an empty value; in neither Go nor Rust did an extra bool result seem necessary to do this.

I don't understand how to do this so I left it as-is for now :). What did you have in mind?

@phritz:

> I think it would be bad if chunk store or the layer above have different semantics depending on the implementation. I can easily imagine that using different databases under the hood could admit subtle behavioral differences. For this reason I think we might consider making more and more explicit statements about the expected behavior of chunk store. That way we can carefully check how closely the implementation matches what we want and know where we have to add some machinery at a level above the database to bring Its behavior in line with what we expect. Questions like the real time and ordering guarantees or lack thereof and whether it is read after write seem like a good place to start. Given our use case we might want to err on the side of easy to reason about for the developer using the chunk store interface as opposed to high performance (ie we are not doing read your rights over the network).

I think that "strict serializability" captures everything you called out here.

@phritz:

> it might be nice to call the higher-level thing something other than "database". There is already going to be a database at the lowest layer namely sqlite or similar. We should definitely not do the noms thing where we have a thingy of the same name at different levels.

Done in other doc.

@phritz:

> in the chunk store interface I might have expected multi get and multiset were you can read or write number of chunks at one time instead of the single chunk oriented interface described above. I'm saying this as someone who knows very little about how all this is going to actually work or about how Noms works. I have no idea if that would be an important aspect of making it efficient but it would be kind of natural based on how I understand the chunk store will be used.

I don't believe that this is currently needed, because transactions are basically filling same role.

Because we're not remote from the db like a classic db service, we don't have to worry about batching to reduce round trips.

That said, we might eventually want a multikey get/set from JavaScript into the repm, because that *is* a sort of RPC. But that's a different layer.

@phritz:

> for the hanging sync head problem it's a pretty simple rule to reason about you just say that it has to be in the graph. If something is not reachable through the graph then it gets garbage collected. Is there any kind of eager writing that would make this problematic like for example do you have to write chunks in the order in which they are found in the graph?

Agree.

@phritz:

> I'm a little unclear in the model described above where the concept of graph comes in. Is it something that is hidden under the hood of a map or is a map part of a type system like in Noms? Or does it come in because we are treating the value bytes as Json?

@arv:

> I feel like there is a lot of implied behavior here when it comes to GC. There is no mention how you determine what a ref is? I'm assuming there is a layer on top of this that is somewhat similar to Noms that defines how a value references another key (or value) for this discussion.

See #3.

**Comment by aboodman** [comment]
This is done enough to close!
