### ISSUE TITLE
Implement refcounting / gc

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#34]
We now have enough of the components in place to implement refcounting and gc in the dag layer. See https://github.com/rocicorp/repc/issues/3#issuecomment-648711429 for proposed design.

**Comment by phritz** [comment]
Need to fix this when GC is implemented: https://github.com/rocicorp/repc/issues/105

**Comment by arv** [comment]
I started working on this... I need to write a detailed design doc for this but here is some general ideas:

 - Store the `count` in the `meta` key-value-pair.
 - setting a head increments the `count` for the target of the head
 - removing a head decrements the `count` of the target
 - When a chunk with `refs` is written or changed the `refs` are followed to update the `count` as needed.
 - When we **commit** we need to iterate over all the meta data and remove chunks that have a `0` `count`.
    - It seems like a bad idea to iterate over all the meta data key-value-pairs here. Should we keep track of all the keys that were touched? We will want that in the future for improved subscribe performance anyway.

**Comment by arv** [comment]
## Algorithm

### Data structure changes:

- Add a count to `meta.fbs`.
  - I'm using `uint16` which has a max value of 65535. Maybe `uint8` is enough but seems too scary.
- `dag::Write` gets a `Set` called `rc_set` for now, which contains all the hashes that have reached `count` 0 during the lifetime of `dag::Write` (the write transaction)
  - This is guarded by `RwLock`.

### Algorithm changes:

- `put_chunk`:
  - New chunks start with a RC of `0`.
    - insert the _hash_ in `rc_set`.
  - We compute a diff compared to the previous chunk of the `refs`. We increment and decrement the referenced chunks as needed.
    - I'm changing `refs` to be sorted on write.
      - This allows `O(n)` diff
      - The size of `refs` is today `<= 3` but it will get larger when we implement real prolly trees.
- `set_head`:
  - Setting a head to a _hash_ increments the `count` for the chunk that _hash_ references and decrements the `count` for the chunk _old hash_ references.
- `change_ref_count`:
  - reads the meta for the chunk with the given _hash_.
  - changes the `count`
    - if `count` reaches `0`:
      - adds the _hash_ to `rc_set`.
      - recursively change the ref count of all the referenced chunks.
    - Otherwise removes the _hash_ from the `rc_set`.
    - Write the `Key::ChunkMeta` with updated count.
- `commit`:
  - Here we remove all chunks (and their meta key) that ended up in `rc_set`, which is all the chunks with a 0 ref count.
  - We do not need to follow the `refs` here since we did that in `change_ref_count`.
    - It is possible that it would be better to follow the refs here? If so we would need to be able to get the old refs before the Write was created.
