### ISSUE TITLE
implement patch

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#90]
probably want to have https://github.com/rocicorp/repc/issues/89 done before this issue so it can be used.

a patch to the client's map is returned by the diffserver:
https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/serve/types/types.go#L19
https://github.com/rocicorp/repc/blob/3678fa5b5fbcce0ed061955ebddafa790565017c/src/embed/sync.rs#L49

currently the diff that is generated by the diffserver is pretty dumb, it operates only at the level of keys and values and not for example with json path within values. this makes the task in this issue easier. 

the task here is to implement patch: https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/kv/patch.go#L122. the patch is to a prolly map https://github.com/rocicorp/repc/blob/master/src/prolly/map.rs#L15 (or maybe to a trait w get/put/has/del?). 

i don't *think* we need diff in repc. could be wrong tho.

**Comment by aboodman** [comment]
We decided in https://github.com/rocicorp/repc/issues/93 to diverge from what replicache-client does for patch. Instead of returning a JSON patch where the value level diffs are expressed using JSON patch directly, every row of the JSON patch will simply be a string containing the entire new value (encoded as a string).

The corresponding diff-server bug is: https://github.com/rocicorp/diff-server/issues/54.

**Comment by phritz** [comment]
closed by https://github.com/rocicorp/repc/pull/123
